version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_KEY=base64:vWWyFxQjB49+qD7EKZDevcBuHxg6H5xnYvGb/BVx1Eg=
            - APP_DEBUG=true
            - APP_URL=http://localhost:8000

            - LOG_CHANNEL=stack
            - LOG_DEPRECATIONS_CHANNEL=null
            - LOG_LEVEL=debug

            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret

            - BROADCAST_DRIVER=log
            - CACHE_DRIVER=redis
            - FILESYSTEM_DISK=local
            - QUEUE_CONNECTION=rabbitmq
            - SESSION_DRIVER=redis
            - SESSION_LIFETIME=120

            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379

            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_VHOST=/
            - RABBITMQ_LOGIN=admin
            - RABBITMQ_PASSWORD=admin
            - RABBITMQ_QUEUE=default
            - RABBITMQ_EXCHANGE_NAME=default

            - L5_SWAGGER_GENERATE_ALWAYS=true
            - L5_SWAGGER_GENERATE_YAML_COPY=true

            - ELASTICSEARCH_HOST=http://localhost:9200

            - MAIL_MAILER=smtp
            - MAIL_HOST=mailhog
            - MAIL_PORT=1025
            - MAIL_USERNAME=null
            - MAIL_PASSWORD=null
            - MAIL_ENCRYPTION=null
            - MAIL_FROM_ADDRESS="hello@example.com"
            - MAIL_FROM_NAME="${APP_NAME}"
        depends_on:
            mysql:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_healthy

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
            interval: 10s
            timeout: 5s
            retries: 5

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ports:
            - "9200:9200"
            - "9300:9300"
        healthcheck:
            test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    mysql-data:

networks:
    default:
        driver: bridge